name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Test with the Go CLI
        run: go test ./...

  tag-release:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - name: Release
        uses: RedSockActions/release_tag@v1.1.6
        with:
          token: ${{ github.token }}
          config_path: version/version.yaml
